name: notify slack schedule about prs

on:
  schedule:
    - cron: '59 22 * * 1-5'  # 매주 월요일부터 금요일까지 한국 시간 07:59에 실행

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: asdsadsaad
        uses: torder-lkj/notify_slack@v1.0.0
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}