name: update D- label schedule

on:
  schedule:
    - cron: '1 15 * * 1-5'  # 매주 월요일부터 금요일까지 한국 시간 00:01에 실행

permissions:
  issues: write
  pull-requests: write

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Use Add D- Label Action
        uses: torder-lkj/update_d_label@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}